export const sounds = [
  {"name":"Death Sound Fortnite","mp3":"death-sound-fortnite.mp3","color":"#ff6b6b"},
  {"name":"Among Us Role Reveal","mp3":"among-us-role-reveal-sound.mp3","color":"#3498db"},
  {"name":"Wait What The Hell","mp3":"Wait-wait-wait-what-the-hell-legend-sound.mp3","color":"#f39c12"},
  {"name":"Victory Sound","mp3":"Victory-sound.mp3","color":"#2ecc71"},
  {"name":"Clinking Glasses","mp3":"Clinking-glasses-sound-effect.mp3","color":"#e74c3c"},
  {"name":"Goofy SpongeBob","mp3":"3D3PVTP5-Goofy-ahh-SpongeBob-sound-.mp3","color":"#9b59b6"},
  {"name":"Womp Womp","mp3":"womp-womp-womp.mp3","color":"#1abc9c"},
  {"name":"Diddy Calculator","mp3":"what-is-this-diddy-blud-doing-on-the-calculator-meme-pesa.mp3","color":"#e67e22"},
  {"name":"Tung Tung Sahur","mp3":"tung-tung-sahur.mp3","color":"#34495e"},
  {"name":"uwu","mp3":"uwu.mp3","color":"#16a085"},
  {"name":"The More You Know","mp3":"the-more-you-know.mp3","color":"#27ae60"},
  {"name":"Tuco Get Out","mp3":"tuco-get-out.mp3","color":"#c0392b"},
  {"name":"Sudden Stop","mp3":"sudden-stop-pause.mp3","color":"#7f8c8d"},
  {"name":"Spiderman Meme","mp3":"spiderman-meme-song.mp3","color":"#f1c40f"},
  {"name":"Sad Violin","mp3":"sad-violin-the-meme-one.mp3","color":"#95a5a6"},
  {"name":"Oh My God Bro","mp3":"oh-my-god-bro-oh-hell-nah-man.mp3","color":"#d35400"},
  {"name":"MLG Air Horn","mp3":"mlg-air-horn.mp3","color":"#8e44ad"},
  {"name":"Nope Meme","mp3":"nope-meme.mp3","color":"#2c3e50"},
  {"name":"Miguel O'Hara","mp3":"miguel-oharris-spider-man-2099.mp3","color":"#2980b9"},
  {"name":"Oi Oi","mp3":"o-o-o-oi-oi-a-eye-eye.mp3","color":"#f39c12"},
  {"name":"Mac Quack","mp3":"mac-quack.mp3","color":"#1abc9c"},
  {"name":"La Grande Combinacion","mp3":"la-grande-combinacion-Meme.mp3","color":"#e74c3c"},
  {"name":"Katseye","mp3":"katseye.mp3","color":"#9b59b6"},
  {"name":"About Drive","mp3":"its-about-Drive.mp3","color":"#3498db"},
  {"name":"Habibi Hamood","mp3":"habibi-hamood.mp3","color":"#2ecc71"},
  {"name":"HE HE HE HA","mp3":"he-he-he-ha-clash-royale-DEEP-FRIED.mp3","color":"#e67e22"},
  {"name":"Funny Laugh","mp3":"haha-funny-laugh.mp3","color":"#f1c40f"},
  {"name":"FNAF Jumpscare","mp3":"fnaf-jumpscare-scream.mp3","color":"#c0392b"},
  {"name":"GO GO GO","mp3":"gopgopgop.mp3","color":"#7f8c8d"},
  {"name":"Fire in the Hole","mp3":"fire-in-the-hole-CS.mp3","color":"#d35400"},
  {"name":"Emotional Damage","mp3":"emotional-damage-meme.mp3","color":"#34495e"},
  {"name":"DUN DUN DUN","mp3":"dun-dun-dunnnnnnnn.mp3","color":"#95a5a6"},
  {"name":"Bluetooth Connected","mp3":"bluetooth-device-connected-asuccesfullay.mp3","color":"#1abc9c"},
  {"name":"Bowler","mp3":"clash-royale-bowler.mp3","color":"#2c3e50"},
  {"name":"Correct Answer","mp3":"correct-answer-gameshow.mp3","color":"#27ae60"},
  {"name":"Cat Laugh","mp3":"cat-laugh-meme-1.mp3","color":"#f39c12"},
  {"name":"Baby Laugh","mp3":"baby-laughing-meme.mp3","color":"#e74c3c"},
  {"name":"Asian Meme Huh","mp3":"asian-meme-huh.mp3","color":"#9b59b6"},
  {"name":"Yes King","mp3":"Yes-King-AHHHHHHHHHHHHHHHH.mp3","color":"#3498db"},
  {"name":"WE ARE CHARLIE KIRK","mp3":"WE-ARE-CHARLIE-KIRK.mp3","color":"#e74c3c"},
  {"name":"Voce Na Mira","mp3":"Voce-Na-Mira-Slowed.mp3","color":"#f1c40f"},
  {"name":"Hooray","mp3":"TheBurntPeanut-Hooray.mp3","color":"#2ecc71"},
  {"name":"TUCA DONKAA","mp3":"TUCA-DONKAA.mp3","color":"#d35400"},
  {"name":"Sukuna Laugh","mp3":"Sukuna-laugh.mp3","color":"#c0392b"},
  {"name":"Steal a Brainrot","mp3":"Steal-a-brainrot.mp3","color":"#7f8c8d"},
  {"name":"Spectre","mp3":"Spectre.mp3","color":"#95a5a6"},
  {"name":"Shimmy Shimmy","mp3":"Shimmy-shimmy.mp3","color":"#1abc9c"},
  {"name":"Lightsaber","mp3":"Sith-Lightsaber-Ignition.mp3","color":"#f39c12"},
  {"name":"Say Drake","mp3":"Say-Drake-I-Heard-You-Like-Em-Young.mp3","color":"#9b59b6"},
  {"name":"Obama Have Dih","mp3":"Obama-Have-Dih.mp3","color":"#3498db"},
  {"name":"Oh Guardian","mp3":"Oh-Guardian.mp3","color":"#2ecc71"},
  {"name":"Pizza Time","mp3":"PeterParkerPizza-Time.mp3","color":"#e74c3c"},
  {"name":"REPO ROBE","mp3":"REPO-ROBE.mp3","color":"#2c3e50"},
  {"name":"Jet2 Holiday","mp3":"Nothing-beats-a-jet2-holiday.mp3","color":"#d35400"},
  {"name":"NECK HURT","mp3":"NECK-HURT-FUNK-Rupertgamingboy.mp3","color":"#8e44ad"},
  {"name":"My Mommy Said No","mp3":"My-mommy-said-no-more-skibidi-meme.mp3","color":"#34495e"},
  {"name":"Mr Beast","mp3":"Mr-Beast-Give-Me-Sum-Money.mp3","color":"#f1c40f"},
  {"name":"Milkaholic","mp3":"Milkaholic.mp3","color":"#e67e22"},
  {"name":"MI BOMBO","mp3":"MI-BOMBO.mp3","color":"#1abc9c"},
  {"name":"Kill Yourself","mp3":"Low-Tier-God-You-should-kill-yourself-NOW.mp3","color":"#c0392b"},
  {"name":"Lizard Lizard","mp3":"Lizard-Lizard-Lizard.mp3","color":"#95a5a6"},
  {"name":"LOOKIE LOKKIE","mp3":"LOOKIE-LOKKIE.mp3","color":"#f39c12"},
  {"name":"Kpop Demon Hunters","mp3":"Kpop-Demon-Hunters.mp3","color":"#9b59b6"},
  {"name":"Kawhi Laugh","mp3":"Kawhi-Leonard-Laugh.mp3","color":"#2ecc71"},
  {"name":"Jordan Peterson","mp3":"Jordan-Peterson-Dreams-About-His-Grandma.mp3","color":"#3498db"},
  {"name":"Bus Is Here","mp3":"Jaydens-bus-is-here.mp3","color":"#e74c3c"},
  {"name":"Symphony Tiktok","mp3":"I-just-want-to-be-part-of-your-symphony-tiktok.mp3","color":"#d35400"},
  {"name":"I Wish I Knew","mp3":"I-WISH-I-KNEW-FUNK-Meme.mp3","color":"#7f8c8d"},
  {"name":"Hello Moto","mp3":"Hello-Moto-Highest-Quality.mp3","color":"#1abc9c"},
  {"name":"Markiplier","mp3":"Hello-everybody-my-name-is-Markiplier.mp3","color":"#2c3e50"},
  {"name":"Fahhh","mp3":"Fahhh.mp3","color":"#f1c40f"},
  {"name":"Golden Dandelion","mp3":"Golden-Dandelion.mp3","color":"#e74c3c"},
  {"name":"Dragon Cannelloni","mp3":"Dragon-Cannelloni.mp3","color":"#3498db"},
  {"name":"They Forgot","mp3":"Dracula-Flow-They-forgot-Im-him.mp3","color":"#9b59b6"},
  {"name":"Doorbell","mp3":"Doorbell.mp3","color":"#2ecc71"},
  {"name":"Doodle Dance","mp3":"Doodle-Dance-Pipe.mp3","color":"#d35400"},
  {"name":"Deez Nuts","mp3":"Deez-Nuts-button.mp3","color":"#f39c12"},
  {"name":"Clown Circus","mp3":"Clown-Circus-music.mp3","color":"#c0392b"},
  {"name":"Devesto","mp3":"Devesto.mp3","color":"#7f8c8d"},
  {"name":"Cave Ambience","mp3":"Cave-ambience.mp3","color":"#34495e"},
  {"name":"Cake At Stake","mp3":"Cake-At-Stake-theme.mp3","color":"#95a5a6"},
  {"name":"Breaking Bad","mp3":"Breaking-Bad-Theme.mp3","color":"#e67e22"},
  {"name":"All My Fellas","mp3":"ALL-all-my-fellas.mp3","color":"#1abc9c"},
  {"name":"67","mp3":"67.mp3","color":"#2ecc71"},
  {"name":"Merry Rizzmas","mp3":"67-Merry-Rizzmas.mp3","color":"#f39c12"}
];